# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:2.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - lint
  - test
  - deploy
# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_19.05
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
  - unset JAVA_HOME
  - pip install planemo


lint:
  stage: lint
  script:
    - pip install flake8 flake8-import-order
    - planemo --version
    - echo ${CI_COMMIT_BEFORE_SHA}
    - git diff --quiet ${CI_COMMIT_BEFORE_SHA} -- ; GIT_DIFF_EXIT_CODE=$?
    # - |
    #   if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
    #       git remote set-branches --add origin master
    #       git fetch
    #       CI_COMMIT_BEFORE_SHA=origin/master...
    #   fi
    - echo ${GIT_DIFF_EXIT_CODE}
    - echo ${CI_COMMIT_BEFORE_SHA}
    - |
      planemo ci_find_repos --exclude_from .tt_skip \
        --output changed_repositories.list
    - cat changed_repositories.list
    - set -e
    - while read -r DIR; do flake8 --exclude=.git,./deprecated/ $DIR; done < changed_repositories.list
    - while read -r DIR; do planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive "$DIR"; done < changed_repositories.list

test:
  stage: test
  script:
    - planemo ci_find_repos --exclude_from .tt_skip --output changed_repositories.list
    - cat changed_repositories.list
    - set -e
    - while read -r DIR; do planemo test --conda_dependency_resolution --conda_auto_install --conda_channels iuc,conda-forge,bioconda,defaults --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" $DIR; done < changed_repositories.list

deploy:
  stage: deploy
  script:
    - cat changed_repositories.list